spring:
  application:
    name: springboot-graphql-example
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/betting1}
    username: ${DB_USERNAME:betadmin}
    password: ${DB_PASSWORD:asdf123_}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql:
          true
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
