spring:
  application:
    name: springboot-graphql-example
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/betting1}
    username: ${DB_USERNAME:betadmin}
    password: ${DB_PASSWORD:asdf123_}
    hikari:
      maximum-pool-size=8
      minimum-idle=4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql:
          true
  graphql:
    path: /graphql
    webSocket:
      path: /subscriptions
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
      path: /graphiql
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
logging:
  level:
    reactor:
      netty:
        http: debug
    org:
      springframework:
        web: debug
        http: debug
        graphql: debug
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


