spring:
  application:
    name: springboot-graphql-example
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/betting1}
    username: ${DB_USERNAME:betadmin}
    password: ${DB_PASSWORD:asdf123_}
  jpa:
    hibernate:
      ddl-auto: update
  graphql:
    path: /graphql
