server:
  port: 80
spring:
  application:
    name: parabolic-betting-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/betting1}
    username: ${DB_USERNAME:betadmin}
    password: ${DB_PASSWORD:asdf123_}
    hikari:
      maximum-pool-size=6
      minimum-idle=4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql:
          true
  graphql:
    path: /private/graphql
    cors:
      allowed-origins: '*'
      allowed-methods: '*'
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
      path: /private/graphiql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://parabolicbet.eu.auth0.com/
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
logging:
  root: DEBUG
  level:
    com:
      npd:
        betting: info
      mysql:
        cj: info
    reactor:
      netty:
        http: error
    org:
      springframework:
        web: DEBUG
        http: error
        graphql: error
        jpa: info
      hibernate:
        SQL: info
        type:
          descriptor:
            sql:
              BasicBinder: info
okta:
  oauth0:
    issuer: https://parabolicbet.eu.auth0.com/
    client-id: IHCyxIXxF8bVJThvviAF583taf9E7HfN
    audience: https://parabolicbet.eu.auth0.com/api/v2/